import { createHash } from "node:crypto";
import { mkdir, readdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const rootDirectory = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const sourceDirectory = path.join(rootDirectory, "!PORTFOLIO");
const mastersDirectory = path.join(rootDirectory, "public", "galeria", "masters");
const thumbsDirectory = path.join(rootDirectory, "public", "galeria", "thumbs");
const manifestPath = path.join(rootDirectory, "src", "data", "galleryManifest.ts");
const supportedExtensions = new Set([".avif", ".jpeg", ".jpg", ".png", ".tif", ".tiff", ".webp"]);
const MASTER_MAX_EDGE = 2400;
const THUMB_WIDTH = 420;

function getPublicUrl(...segments) {
  // Relative (no leading slash) so GitHub Pages project base `/hatemecha-web/` resolves correctly.
  return segments.map((segment) => encodeURIComponent(segment)).join("/");
}

function getStableId(filename) {
  return createHash("sha1").update(filename).digest("hex").slice(0, 10);
}

function slugifyFilename(filename) {
  const parsed = path.parse(filename);
  const slug = parsed.name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "imagen";
}

function getDisplayDimensions(metadata) {
  const width = metadata.width ?? 1;
  const height = metadata.height ?? 1;
  const orientation = metadata.orientation ?? 1;

  if (orientation >= 5 && orientation <= 8) {
    return { width: height, height: width };
  }

  return { width, height };
}

function getAltText(filename) {
  return path
    .parse(filename)
    .name
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function buildManifest(items) {
  return `// Generated by scripts/sync-gallery.mjs. Do not edit by hand.
export type GalleryItem = {
  id: string;
  src: string;
  thumbSrc: string;
  width: number;
  height: number;
  alt: string;
  filename: string;
};

export const galleryItems: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;
}

async function isNewerThan(sourcePath, outputPath) {
  try {
    const [sourceStats, outputStats] = await Promise.all([stat(sourcePath), stat(outputPath)]);
    return sourceStats.mtimeMs > outputStats.mtimeMs;
  } catch {
    return true;
  }
}

async function getSourceFiles() {
  await mkdir(sourceDirectory, { recursive: true });
  await mkdir(mastersDirectory, { recursive: true });
  await mkdir(thumbsDirectory, { recursive: true });

  const entries = await readdir(sourceDirectory, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && supportedExtensions.has(path.extname(entry.name).toLowerCase()))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b, "es", { numeric: true, sensitivity: "base" }));
}

async function syncGallery() {
  const files = await getSourceFiles();

  if (files.length === 0) {
    console.log(
      "gallery: no images in !PORTFOLIO — keeping committed public/galeria assets and galleryManifest.ts"
    );
    return;
  }

  const items = [];

  for (const filename of files) {
    const id = getStableId(filename);
    const baseName = `${slugifyFilename(filename)}-${id}`;
    const masterFilename = `${baseName}.webp`;
    const thumbFilename = `${baseName}.webp`;
    const sourcePath = path.join(sourceDirectory, filename);
    const masterPath = path.join(mastersDirectory, masterFilename);
    const thumbPath = path.join(thumbsDirectory, thumbFilename);

    const needsMaster = await isNewerThan(sourcePath, masterPath);
    const needsThumb = await isNewerThan(sourcePath, thumbPath);

    if (needsMaster) {
      await sharp(sourcePath)
        .rotate()
        .resize({
          width: MASTER_MAX_EDGE,
          height: MASTER_MAX_EDGE,
          fit: "inside",
          withoutEnlargement: true
        })
        .webp({
          effort: 5,
          quality: 82
        })
        .toFile(masterPath);
    }

    if (needsThumb) {
      await sharp(sourcePath)
        .rotate()
        .resize({
          width: THUMB_WIDTH,
          withoutEnlargement: true
        })
        .webp({
          effort: 5,
          quality: 78
        })
        .toFile(thumbPath);
    }

    const masterMetadata = await sharp(masterPath).metadata();
    const { width, height } = getDisplayDimensions(masterMetadata);

    items.push({
      id,
      src: getPublicUrl("galeria", "masters", masterFilename),
      thumbSrc: getPublicUrl("galeria", "thumbs", thumbFilename),
      width,
      height,
      alt: getAltText(filename),
      filename
    });
  }

  await writeFile(manifestPath, buildManifest(items));

  const keepMasters = new Set(items.map((item) => path.basename(item.src)));
  const keepThumbs = new Set(items.map((item) => path.basename(item.thumbSrc)));
  let pruned = 0;

  for (const filename of await readdir(mastersDirectory)) {
    if (!filename.endsWith(".webp") || keepMasters.has(filename)) continue;
    await unlink(path.join(mastersDirectory, filename));
    pruned += 1;
  }

  for (const filename of await readdir(thumbsDirectory)) {
    if (!filename.endsWith(".webp") || keepThumbs.has(filename)) continue;
    await unlink(path.join(thumbsDirectory, filename));
    pruned += 1;
  }

  console.log(
    `gallery: synced ${items.length} image${items.length === 1 ? "" : "s"} from !PORTFOLIO` +
      (pruned > 0 ? ` (pruned ${pruned} orphan${pruned === 1 ? "" : "s"})` : "")
  );
}

syncGallery().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
