import { createHash } from "node:crypto";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const rootDirectory = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const originalsDirectory = path.join(rootDirectory, "public", "galeria", "originales");
const thumbsDirectory = path.join(rootDirectory, "public", "galeria", "thumbs");
const manifestPath = path.join(rootDirectory, "src", "data", "galleryManifest.ts");
const supportedExtensions = new Set([".avif", ".jpeg", ".jpg", ".png", ".tif", ".tiff", ".webp"]);

function getPublicUrl(...segments) {
  return `/${segments.map((segment) => encodeURIComponent(segment)).join("/")}`;
}

function getStableId(filename) {
  return createHash("sha1").update(filename).digest("hex").slice(0, 10);
}

function slugifyFilename(filename) {
  const parsed = path.parse(filename);
  const slug = parsed.name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "imagen";
}

function getDisplayDimensions(metadata) {
  const width = metadata.width ?? 1;
  const height = metadata.height ?? 1;
  const orientation = metadata.orientation ?? 1;

  if (orientation >= 5 && orientation <= 8) {
    return { width: height, height: width };
  }

  return { width, height };
}

function getAltText(filename) {
  return path
    .parse(filename)
    .name
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function buildManifest(items) {
  return `// Generated by scripts/sync-gallery.mjs. Do not edit by hand.
export type GalleryItem = {
  id: string;
  src: string;
  thumbSrc: string;
  width: number;
  height: number;
  alt: string;
  filename: string;
};

export const galleryItems: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;
}

async function getOriginalFiles() {
  await mkdir(originalsDirectory, { recursive: true });
  await mkdir(thumbsDirectory, { recursive: true });

  const entries = await readdir(originalsDirectory, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && supportedExtensions.has(path.extname(entry.name).toLowerCase()))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b, "es", { numeric: true, sensitivity: "base" }));
}

async function syncGallery() {
  const files = await getOriginalFiles();
  const items = [];

  for (const filename of files) {
    const id = getStableId(filename);
    const thumbFilename = `${slugifyFilename(filename)}-${id}.webp`;
    const originalPath = path.join(originalsDirectory, filename);
    const thumbPath = path.join(thumbsDirectory, thumbFilename);
    const image = sharp(originalPath);
    const metadata = await image.metadata();
    const { width, height } = getDisplayDimensions(metadata);

    await sharp(originalPath)
      .rotate()
      .resize({
        width: 420,
        withoutEnlargement: true
      })
      .webp({
        effort: 5,
        quality: 78
      })
      .toFile(thumbPath);

    items.push({
      id,
      src: getPublicUrl("galeria", "originales", filename),
      thumbSrc: getPublicUrl("galeria", "thumbs", thumbFilename),
      width,
      height,
      alt: getAltText(filename),
      filename
    });
  }

  await writeFile(manifestPath, buildManifest(items));
  console.log(`gallery: synced ${items.length} image${items.length === 1 ? "" : "s"}`);
}

syncGallery().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
