import { createHash } from "node:crypto";
import { copyFile, mkdir, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const rootDirectory = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const sourceDirectory = path.join(rootDirectory, "!PORTFOLIO");
const viewDirectory = path.join(rootDirectory, "public", "galeria", "view");
const thumbsDirectory = path.join(rootDirectory, "public", "galeria", "thumbs");
const legacyMastersDirectory = path.join(rootDirectory, "public", "galeria", "masters");
const manifestPath = path.join(rootDirectory, "src", "data", "galleryManifest.ts");
const supportedExtensions = new Set([".avif", ".jpeg", ".jpg", ".png", ".tif", ".tiff", ".webp"]);
/** Lightbox/display max edge — kept modest for GH Pages weight (~was 2400 masters). */
const VIEW_MAX_EDGE = 1600;
const THUMB_WIDTH = 420;

function getPublicUrl(...segments) {
  // Relative (no leading slash) so GitHub Pages project base `/hatemecha-web/` resolves correctly.
  return segments.map((segment) => encodeURIComponent(segment)).join("/");
}

function getStableId(filename) {
  return createHash("sha1").update(filename).digest("hex").slice(0, 10);
}

function slugifyFilename(filename) {
  const parsed = path.parse(filename);
  const slug = parsed.name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "imagen";
}

function getDisplayDimensions(metadata) {
  const width = metadata.width ?? 1;
  const height = metadata.height ?? 1;
  const orientation = metadata.orientation ?? 1;

  if (orientation >= 5 && orientation <= 8) {
    return { width: height, height: width };
  }

  return { width, height };
}

function getAltText(filename) {
  return path
    .parse(filename)
    .name
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function buildManifest(items) {
  return `// Generated by scripts/sync-gallery.mjs. Do not edit by hand.
export type GalleryItem = {
  id: string;
  src: string;
  thumbSrc: string;
  width: number;
  height: number;
  alt: string;
  filename: string;
};

export const galleryItems: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;
}

async function isNewerThan(sourcePath, outputPath) {
  try {
    const [sourceStats, outputStats] = await Promise.all([stat(sourcePath), stat(outputPath)]);
    return sourceStats.mtimeMs > outputStats.mtimeMs;
  } catch {
    return true;
  }
}

async function exceedsMaxEdge(outputPath, maxEdge) {
  try {
    const metadata = await sharp(outputPath).metadata();
    const edge = Math.max(metadata.width ?? 0, metadata.height ?? 0);
    return edge > maxEdge;
  } catch {
    return true;
  }
}

async function writeWebpAtomic(tempPath, finalPath, pipeline) {
  await pipeline.toFile(tempPath);
  try {
    await rename(tempPath, finalPath);
  } catch {
    await copyFile(tempPath, finalPath);
    await unlink(tempPath).catch(() => undefined);
  }
}

async function pruneDirectory(directory, keepNames) {
  let pruned = 0;
  let entries = [];
  try {
    entries = await readdir(directory);
  } catch {
    return 0;
  }

  for (const filename of entries) {
    if (!filename.endsWith(".webp") || filename.endsWith(".tmp.webp")) continue;
    if (keepNames?.has(filename)) continue;
    try {
      await unlink(path.join(directory, filename));
      pruned += 1;
    } catch {
      // File may be locked by the Windows/Vite file watcher.
    }
  }

  return pruned;
}

async function getSourceFiles() {
  await mkdir(sourceDirectory, { recursive: true });
  await mkdir(viewDirectory, { recursive: true });
  await mkdir(thumbsDirectory, { recursive: true });

  const entries = await readdir(sourceDirectory, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && supportedExtensions.has(path.extname(entry.name).toLowerCase()))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b, "es", { numeric: true, sensitivity: "base" }));
}

async function syncGallery() {
  const files = await getSourceFiles();

  if (files.length === 0) {
    console.log(
      "gallery: no images in !PORTFOLIO — keeping committed public/galeria assets and galleryManifest.ts"
    );
    return;
  }

  const items = [];

  for (const filename of files) {
    const id = getStableId(filename);
    const baseName = `${slugifyFilename(filename)}-${id}`;
    const viewFilename = `${baseName}.webp`;
    const thumbFilename = `${baseName}.webp`;
    const sourcePath = path.join(sourceDirectory, filename);
    const viewPath = path.join(viewDirectory, viewFilename);
    const thumbPath = path.join(thumbsDirectory, thumbFilename);

    const needsView =
      (await isNewerThan(sourcePath, viewPath)) || (await exceedsMaxEdge(viewPath, VIEW_MAX_EDGE));
    const needsThumb = await isNewerThan(sourcePath, thumbPath);

    if (needsView) {
      await writeWebpAtomic(
        `${viewPath}.tmp.webp`,
        viewPath,
        sharp(sourcePath)
          .rotate()
          .resize({
            width: VIEW_MAX_EDGE,
            height: VIEW_MAX_EDGE,
            fit: "inside",
            withoutEnlargement: true
          })
          .webp({
            effort: 5,
            quality: 78
          })
      );
    }

    if (needsThumb) {
      await writeWebpAtomic(
        `${thumbPath}.tmp.webp`,
        thumbPath,
        sharp(sourcePath)
          .rotate()
          .resize({
            width: THUMB_WIDTH,
            withoutEnlargement: true
          })
          .webp({
            effort: 5,
            quality: 78
          })
      );
    }

    const viewMetadata = await sharp(viewPath).metadata();
    const { width, height } = getDisplayDimensions(viewMetadata);

    items.push({
      id,
      src: getPublicUrl("galeria", "view", viewFilename),
      thumbSrc: getPublicUrl("galeria", "thumbs", thumbFilename),
      width,
      height,
      alt: getAltText(filename),
      filename
    });
  }

  await writeFile(manifestPath, buildManifest(items));

  const keepViews = new Set(items.map((item) => path.basename(item.src)));
  const keepThumbs = new Set(items.map((item) => path.basename(item.thumbSrc)));
  let pruned = await pruneDirectory(viewDirectory, keepViews);
  pruned += await pruneDirectory(thumbsDirectory, keepThumbs);
  // Legacy 2400px masters folder — drop when unlocked.
  pruned += await pruneDirectory(legacyMastersDirectory, null);

  console.log(
    `gallery: synced ${items.length} image${items.length === 1 ? "" : "s"} from !PORTFOLIO` +
      (pruned > 0 ? ` (pruned ${pruned} orphan${pruned === 1 ? "" : "s"})` : "")
  );
}

syncGallery().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
