// Generated by scripts/sync-gallery.mjs. Do not edit by hand.
export type GalleryItem = {
  id: string;
  src: string;
  thumbSrc: string;
  width: number;
  height: number;
  alt: string;
  filename: string;
};

export const galleryItems: GalleryItem[] = [];
